version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: jira
      MINIO_ROOT_PASSWORD: jirajira
    volumes:
      - ./.minio/data:/data
    command: server /data --console-address ":9001"
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./.pg/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jira
      POSTGRES_DB: jira
      POSTGRES_USER: jira